export default {
  env: 'uat',
  // 用户环境
  user: 'user_uat',
  // 账号绑钉钉的第三方dingId
  dingId: 'dingoar4eteffscespfvo8',
  dingBackUrl: 'https://uat-www.homestyler.com/cn/static/ding.html',
  // 登录链接
  loginUrl: 'https://uat-rms.homestyler.com/sso',
  // 网关
  gateway: 'https://aly-uat-api.homestyler.com',
  // 商城
  mall: 'https://uat-mall.homestyler.com/cn/',
  // 论坛
  bbs: 'https://uat-bbs.homestyler.com/cn/',
  // 案例
  case: 'https://uat-design.homestyler.com/cn/',
  // 商家平台
  erchantmP: 'https://uat-b.homestyler.com',
  // 全国门店
  nationaltoresS: 'https://uat-www.homestyler.com/cn/static/pages/map/index.html',
  // 装修服务
  renovation: 'https://uat-www.homestyler.com/cn/taocan',
  // 设计师主页
  designer: 'https://uat-designer.homestyler.com/cn/',
  // 新版首页
  newHome: 'https://uat-www.homestyler.com/cn/',
  // 3d
  design3d: 'https://uat-3d.homestyler.com/cn/',
  // oss图片地址
  imgUrl: 'https://shejijia-uat.oss-cn-beijing.aliyuncs.com',
  // 个人中心
  newpPersonal: 'https://uat-my.homestyler.com/cn/',
  sso: 'https://aly-uat-api.homestyler.com',
  // robin
  Robin: 'https://jr-uat-pim.homestyler.com',
  // robinModel
  RobinModel: 'https://jr-uat-pbo.homestyler.com'
}
