export default {
  env: 'prod',
  // 用户环境
  user: 'user',
  // 账号绑钉钉的第三方dingId
  dingId: 'dingoar4eteffscespfvo8',
  dingBackUrl: 'https://www.homestyler.com/cn/static/ding.html',
  // 登录链接
  loginUrl: 'https://rms.homestyler.com/sso',
  // 网关
  gateway: 'https://api.homestyler.com',
  // 商城
  mall: 'https://mall.homestyler.com/cn/',
  // 论坛
  bbs: 'https://bbs.homestyler.com/cn/',
  // 案例
  case: 'https://design.homestyler.com/cn/',
  // 商家平台
  erchantmP: 'https://b.homestyler.com',
  // 全国门店
  nationaltoresS: 'https://www.homestyler.com/cn/static/pages/map/index.html',
  // 装修服务
  renovation: 'https://www.homestyler.com/cn/taocan',
  // 设计师主页
  designer: 'https://designer.homestyler.com/cn/',
  // 新版首页
  newHome: 'https://www.homestyler.com/cn/',
  // 3d
  design3d: 'https://3d.homestyler.com/cn/',
  // oss图片地址
  imgUrl: 'https://img.homestyler.com',
  // 个人中心
  newpPersonal: 'https://my.homestyler.com/cn/',
  sso: 'https://api.homestyler.com',
  // robin
  Robin: 'https://jr-uat-pim.homestyler.com',
  // robinModel
  RobinModel: 'https://jr-uat-pbo.homestyler.com'
}
